server:
  port: 8000

jleo:
  jcontrol:
    loginUrl: /login
    interceptUrl: /**
    securityKey: jleo

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/aim
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver